const DIRECTION = {
  BOTTOM: "bottom",
  TOP: "top",
  LEFT: "left",
  RIGHT: "right"
};
const VERTICAL_DIRECTIONS = [DIRECTION.BOTTOM, DIRECTION.TOP];
const POSITIVE_DIRECTIONS = [DIRECTION.BOTTOM, DIRECTION.RIGHT];

export { DIRECTION, VERTICAL_DIRECTIONS, POSITIVE_DIRECTIONS };
